name: Workflow Demo

on: [push]

jobs:
  build_job1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: upload text file
      uses: actions/upload-artifact@v4
      with:
        name: hello-artifact    #name of artifact name to download the file within it...
        path: hello.txt




  jobs:
      needs: build_job1
      name: build_job2
      runs-on: ubuntu-latest

      steps:
      - name: Downloading Artifact 
        uses: actions/download-artifact@v4
        with:
         name: hello-artifact       #must mention name of artifact for downloading the file within it.

      - run: ls -lah && more hello.txt